config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "lists#index"
  resources :movies, only: [:index, :show]
  resources :lists do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6}
  validates :movie, uniqueness: { scope: :list}
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo
  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :find_list, only: [:new, :create]
  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private
  def find_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :find_list, only: [:show, :edit, :update, :destroy]
  def index
    @lists = List.all
  end

  def show;end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def edit;end

  def update
    @list.update(list_params)
    redirect_to list_path(@list)
  end

  def destroy
    @list.destroy
    redirect_to lists_path
  end

  private

  def find_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<%= simple_form_for [ @list, @bookmark ] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit "Add to list", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(list) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

app/views/lists/edit.html.erb
<%= render "form", list: @list %>

app/views/lists/index.html.erb
<nav class= "navbar navbar-expand-lg navbar-light bg-light justify-content-between">
  <%= image_tag "popcorn.png", alt: "popcorn photo", width: 50, height: 50 %>
  <div class = "nav justify-content-end">
    <%= link_to 'My lists', lists_path%>
    <%= link_to "New list", new_list_path%>
  </div>
</nav>

<div class = "container-fluid">
  <h2>Save any kind of movies</h2>
</div>

<div class="container">
  <div class = "d-flex justify-content-between"
    <h3>My Lists</h3>
    <%= link_to "Create a movie list", new_list_path, class: "btn btn-success" %>
  </div>

  <div class = "d-flex flex-row bd-highlight">
        <% @lists.each do |list| %>
          <div class = "card me-3">
            <%= cl_image_tag list.photo.key, height: 200, width: 300, crop: :fill %>
            <div class="card-img-overlay">
              <%= link_to list.name, list_path(list), id: "link" %>
            </div>
          </div>
        <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<%= render "form", list: @list %>

app/views/lists/show.html.erb
<nav class= "navbar navbar-expand-lg navbar-light bg-light justify-content-between">
  <%= image_tag "popcorn.png", alt: "popcorn photo", width: 50, height: 50 %>
  <div class = "nav justify-content-end">
    <%= link_to 'My lists', lists_path%>
    <%= link_to "New list", new_list_path%>
  </div>
</nav>

<div class = "container-fluid">
  <h2> <%= @list.name %></h2>
  <%= cl_image_tag @list.photo.key, height: 200, width: 500, crop: :fill, class: "img-fluid" %>
</div>

<div class="container">

<%= link_to "Add a new bookmark", new_list_bookmark_path(@list), class: "btn btn-success text-end" %>


<div class="list-group d-flex flex-row">
  <% @list.bookmarks.each do |bookmark| %>
    <div class = "card">
      <%= image_tag "#{bookmark.movie.poster_url}", alt: "popcorn photo", width: 150, height: 200 %>
      <div class = "card-body">
        <h4><%= bookmark.movie.title %> - <%= bookmark.movie.rating %> ⭐</h4>
        <p><%= bookmark.movie.overview %></p>
        <p>"<%= bookmark.comment %>""</p>
      </div>
      <%= link_to 'Remove from list', bookmark_path(bookmark), method: :delete, data: {confirm: 'Are you sure?'} %>
    </div>
  <% end %>
</div>
<%= link_to 'update', edit_list_path(@list), class: "btn btn-info" %>
<%= link_to 'delete list', list_path(@list), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger" %>
</div>

app/views/movies/index.html.erb
<h1> Movies </h1>
<ol class="list-group">
<% @movies.each do |movie| %>
  <li class="list-group-item"><%= link_to movie.title, movie_path(movie) %></li>
<% end %>
</ol>

app/views/movies/show.html.erb
<h1> <%= @movie.title %></h1>
<h4> ⭐️<%= @movie.rating %></h4>
<p><%= @movie.overview %></p>
<%= link_to "Back" , movies_path %>